project:
  type: website
  output-dir: docs

website:
  title: "Laboratorio de Agrometeorología"
  site-url: "https://agromet-lab.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: lineas.qmd
        text: Líneas de trabajo
      - href: proyectos.qmd
        text: Proyectos de investigación
      - href: informes.qmd
        text: Informes
      - href: publicaciones.qmd
        text: Publicaciones
      - href: equipo.qmd
        text: Equipo
      - href: contacto.qmd
        text: Contacto
  page-footer:
    left: |
      <div class="brand-logos footer-logos">
        <img src="inta_logo2.png" alt="INTA" />
      </div>

format:
  html:
    theme:
      - flatly
      - darkly
    css: styles.css
    respect-user-color-scheme: true
    toc: false


editor: visual

