project:
  type: website
  output-dir: docs

website:
  title: "Laboratorio de Agrometeorología"
  site-url: "https://agromet-lab.github.io"
  navbar:
    logo: logo_labo.png
    left:
      - href: index.qmd
      - href: lineas.qmd
        text: Líneas de trabajo
      - href: proyectos.qmd
        text: Proyectos de investigación
      - href: informes.qmd
        text: Informes
      - href: publicaciones.qmd
        text: Publicaciones
      - href: equipo.qmd
        text: Equipo

        
  page-footer:
    center: |
      <hr class="footer-line">
      <div class="footer-bottom">
        © <span id="year"></span> Laboratorio de Agrometeorología, INTA Balcarce. 
        Todos los derechos reservados. 
        Web diseñada por Nuria Lewczuk
        <a href="https://github.com/Nuria1982" 
           target="_blank" 
           class="footer-github">
          <img src="github.png" alt="github" />
        </a>
      </div>

format:
  html:
    theme:
      - Flatly
      - darkly
    
    css: styles.css
    include-after-body: footer-scripts.html
    respect-user-color-scheme: true
    toc: false


editor: source

