project:
  type: website
  output-dir: docs

website:
  title: "Laboratorio de Agrometeorología"
  site-url: "https://agromet-lab.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - about.qmd
      - href: lineas.qmd
        text: Líneas de trabajo
      - href: informes.qmd
        text: Informes
      - href: equipo.qmd
        text: Equipo
      - href: contacto.qmd
        text: Contacto

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    respect-user-color-scheme: true
    toc: true


editor: visual

